# Generated by Django 4.1.7 on 2023-03-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('idcats', models.AutoField(db_column='idCats', primary_key=True, serialize=False)),
                ('nickname', models.CharField(db_column='Nickname', max_length=45)),
                ('breed', models.CharField(db_column='Breed', max_length=45)),
                ('gender', models.CharField(db_column='Gender', max_length=45)),
                ('fur', models.CharField(db_column='Fur', max_length=45)),
                ('character', models.CharField(db_column='Character', max_length=45)),
            ],
        ),
    ]