# Generated by Django 4.1.7 on 2023-03-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cats',
            table='cats',
        ),
    ]
