# Generated by Django 4.1.7 on 2023-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout_app', '0003_alter_cats_options_cats_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='gender',
            field=models.CharField(choices=[('Мальчик', 'Мальчик'), ('Девочка', 'Девочка')], db_column='Gender', max_length=45),
        ),
        migrations.AlterField(
            model_name='cats',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', null=True, upload_to='img/'),
        ),
    ]
