# Generated by Django 4.1.7 on 2023-04-17 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout_app', '0004_alter_cats_gender_alter_cats_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='cats',
            name='fur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='layout_app.furcolor'),
        ),
    ]
