# Generated by Django 4.1.7 on 2023-06-07 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout_app', '0005_furcolor_alter_cats_fur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='cats',
            name='character',
        ),
        migrations.AlterField(
            model_name='cats',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='layout_app.breed'),
        ),
    ]
