# Generated by Django 4.1.7 on 2023-06-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout_app', '0006_breed_remove_cats_character_alter_cats_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('idfeed', models.AutoField(db_column='idfeed', primary_key=True, serialize=False)),
                ('feedname', models.CharField(max_length=45)),
                ('feedkg', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('idtoy', models.AutoField(primary_key=True, serialize=False)),
                ('toyname', models.CharField(max_length=45)),
                ('toycount', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.AlterModelOptions(
            name='furcolor',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
    ]
