# Generated by Django 4.1.7 on 2023-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout_app', '0007_feed_toys_alter_breed_options_alter_furcolor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('fillid', models.AutoField(primary_key=True, serialize=False)),
                ('fillkg', models.IntegerField()),
            ],
        ),
    ]
