# Generated by Django 4.1.7 on 2023-06-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout_app', '0008_filler'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
