# Generated by Django 4.1.7 on 2023-06-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout_app', '0009_cats_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeCat',
            fields=[
                ('idtiket', models.AutoField(primary_key=True, serialize=False)),
                ('cl_name', models.CharField(max_length=40)),
                ('cl_number', models.CharField(max_length=20)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='layout_app.cats')),
            ],
        ),
    ]
